export const countries = [
  { code: 'EG', nameAr: 'مصر', nameEn: 'Egypt' },
  { code: 'SA', nameAr: 'السعودية', nameEn: 'Saudi Arabia' },
  { code: 'AE', nameAr: 'الإمارات', nameEn: 'UAE' },
  { code: 'KW', nameAr: 'الكويت', nameEn: 'Kuwait' },
  { code: 'QA', nameAr: 'قطر', nameEn: 'Qatar' },
  { code: 'BH', nameAr: 'البحرين', nameEn: 'Bahrain' },
  { code: 'OM', nameAr: 'عمان', nameEn: 'Oman' },
  { code: 'JO', nameAr: 'الأردن', nameEn: 'Jordan' },
  { code: 'LB', nameAr: 'لبنان', nameEn: 'Lebanon' },
  { code: 'SY', nameAr: 'سوريا', nameEn: 'Syria' },
  { code: 'IQ', nameAr: 'العراق', nameEn: 'Iraq' },
  { code: 'PS', nameAr: 'فلسطين', nameEn: 'Palestine' },
  { code: 'YE', nameAr: 'اليمن', nameEn: 'Yemen' },
  { code: 'LY', nameAr: 'ليبيا', nameEn: 'Libya' },
  { code: 'TN', nameAr: 'تونس', nameEn: 'Tunisia' },
  { code: 'DZ', nameAr: 'الجزائر', nameEn: 'Algeria' },
  { code: 'MA', nameAr: 'المغرب', nameEn: 'Morocco' },
  { code: 'SD', nameAr: 'السودان', nameEn: 'Sudan' },
  { code: 'US', nameAr: 'أمريكا', nameEn: 'United States' },
  { code: 'UK', nameAr: 'بريطانيا', nameEn: 'United Kingdom' },
  { code: 'CA', nameAr: 'كندا', nameEn: 'Canada' },
  { code: 'DE', nameAr: 'ألمانيا', nameEn: 'Germany' },
  { code: 'FR', nameAr: 'فرنسا', nameEn: 'France' },
  { code: 'OTHER', nameAr: 'أخرى', nameEn: 'Other' },
];
